name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore './OSRS Groceries/'
    - name: Build
      run: dotnet build 'OSRS Groceries/OSRS Groceries.csproj' --no-restore

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Tests
      run: dotnet test OSRS-Groceries-back-end/OSRS Groceries.Tests.csproj
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: 'OSRS Groceries'
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/osrsgroceriesbackend:latest
